apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-pod
  name: nginx-pod
  namespace: mealie
spec:
  volumes:
    - name: scratch-volume
      emptyDir:
        sizeLimit: 500Mi
    - name: mealie-pv-storage
      persistentVolumeClaim:
        claimName: mealie-data
  containers:
  - image: nginx
    name: nginx-pod
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
      - mountPath: /app/data
        name: mealie-pv-storage 
  - image: busybox
    name: busybox
    command: ["/bin/sh", "-c"]
    args: ["sleep 1000"]
    volumeMounts:
      - mountPath: /scratch
        name: scratch-volume
      - mountPath: /app/data
        name: mealie-pv-storage 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
